### PR TITLE
Add Reddit Scripts

### PR DESCRIPTION
**Pull request by adhirajpandey**
## Description

Added some scripts which helps in extracting subscribed subreddits from reddit, and join subreddits which are present in file : subreddits.txt.

This can probably be used to move joined subreddits from one account to new reddit account.

### CODE REVIEW

**Comment by endormi** [comment]
Thank you! I'll check this out at some point and will maybe merge.

**Comment by endormi** [comment]
To merge this, I'd want to see the subs.txt file ignored with a sample.subs.txt (or whichever name you choose) instead and then it being mentioned in README.md.

**Comment by adhirajpandey** [comment]
Made changes as mentioned

**Comment by endormi** [comment]
Thanks! Can you also add it to the gitignore and maybe try to fix the flake8 errors? I can't check this out fully right now, but will do so later on today. I really appreciate this idea!

**Comment by adhirajpandey** [comment]
Got it.

**Comment by endormi** [comment]
LGTM! I'll do some very small additions.

**Pull request merged**
